import {createHash,createPrivateKey,createPublicKey,sign} from "node:crypto";
const id=(prefix,c)=>prefix+c.repeat(21);
const W=id("vlw_","w"),T=id("vlt_","t"),I=id("vli_","i"),Q=id("vlq_","q");
const SA={id:id("vls_","a"),profile:"langsmith-runs/1",namespace:"lab",project:"ls"};
const SB={id:id("vls_","b"),profile:"langfuse-observations/1",namespace:"lab",project:"lf"};
const SC={id:id("vls_","c"),profile:"braintrust-spans/1",namespace:"lab",project:"bt"};
const ZERO="0".repeat(64),ONE="1".repeat(64),D1=id("vld_","d"),D2=id("vld_","e");
const stable=x=>Array.isArray(x)?x.map(stable):x!==null&&typeof x==="object"?Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])])):x;
const J=x=>Buffer.from(JSON.stringify(stable(x)));
const H=x=>createHash("sha256").update(x).digest("hex");
const D=(tag,x)=>H(Buffer.concat([Buffer.from(tag),Buffer.from([0]),J(x)]));
const sorted=xs=>[...xs].sort((a,b)=>Buffer.compare(J(a),J(b)));
const key=(c,hex)=>{const secret=createPrivateKey({key:Buffer.concat([Buffer.from("302e020100300506032b657004220420","hex"),Buffer.from(hex.repeat(32),"hex")]),format:"der",type:"pkcs8"});return {id:id("vlk_",c),secret,public:createPublicKey(secret).export({format:"der",type:"spki"}).subarray(-32).toString("base64url")};};
const KA=key("k","44"),K1=key("l","11"),K2=key("m","22"),K3=key("n","33");
const signed=(tag,body,k)=>{const hash=D(tag,body);return {body,hash,signature:sign(null,Buffer.concat([Buffer.from(tag.replace("/1","-SIGN/1")),Buffer.from([0]),Buffer.from(hash,"hex")]),k.secret).toString("base64url")};};
const agent=subject=>({namespace:"lab",subject,principal:null});
const policy={digest:ONE,version:"policy-1",decision:"ALLOW"};
const step=body=>({body,hash:D("VL-STEP/1",body)});
const n=(source,record,parents=[],patch={})=>step({v:1,workspace:W,trace:T,source:source.id,profile:source.profile,record,native_trace:"native-"+source.project,native_span:record,parents,agent:null,policy:null,offers:[],accept:null,attachments:[],...patch});
const A=n(SA,"a",[],{agent:agent("alice"),policy,offers:[{id:D1,child_source:SB.id,child_agent:agent("bob"),scope:ONE}]});
const B=n(SB,"b",[],{agent:agent("bob"),policy,offers:[{id:D2,child_source:SC.id,child_agent:agent("cara"),scope:ONE}],accept:{id:D1,parent:{source:SA.id,record:"a",hash:A.hash},scope:ONE}});
const C=n(SC,"c",[],{agent:agent("cara"),policy,accept:{id:D2,parent:{source:SB.id,record:"b",hash:B.hash},scope:ONE}});
const origin=(s,k,seq="1",prev=ZERO)=>signed("VL-ORIGIN/1",{v:1,workspace:W,source:s.body.source,stream:"main",seq,prev,step:s.hash,key:k.id},k);
const OA=origin(A,K1),OB=origin(B,K2),OC=origin(C,K3);
const edge=(p,c,delegation,scope)=>{const body={v:1,trace:T,parent:p.hash,child:c.hash,kind:delegation===null?"NATIVE_PARENT":"DELEGATES",delegation,scope};return {body,hash:D("VL-EDGE/1",body)};};
const AB=edge(A,B,D1,ONE),BC=edge(B,C,D2,ONE);
const gap=(code,subject,related=[])=>({code,subject,related:[...related].sort()});
const cmp=(a,b)=>a<b?-1:a>b?1:0;
const graph=(steps,origins,edges,gaps)=>({v:1,workspace:W,trace:T,steps:steps.map(x=>x.hash).sort(),origins:[...new Set(origins.map(x=>x.hash))].sort(),edges:edges.map(x=>x.hash).sort(),gaps:[...gaps].sort((a,b)=>cmp(a.code,b.code)||cmp(a.subject,b.subject)||Buffer.compare(J(a.related),J(b.related)))});
const M0=graph([],[],[],[]),G0=D("VL-GRAPH/1",M0);
const M1=graph([A],[OA],[],[gap("ACCEPT_MISSING",A.hash)]);
const M2=graph([A,B],[OA,OB],[AB],[gap("ACCEPT_MISSING",B.hash)]);
const M3=graph([A,B,C],[OA,OB,OC],[AB,BC],[]);
const metadata=s=>({v:1,trace_id:T,agent:s.body.agent,policy:s.body.policy,offers:s.body.offers,accept:s.body.accept,attachments:s.body.attachments});
const RA={id:"a",trace_id:"native-ls",parent_run_id:null,extra:{metadata:{vislineage:metadata(A)}}};
const RB={id:"b",traceId:"native-lf",parentObservationId:null,metadata:{vislineage:metadata(B)}};
const RC={id:"c",span_id:"c",root_span_id:"native-bt",span_parents:[],metadata:{vislineage:metadata(C)}};
const req=(importId,source,row,o)=>({import:importId,trace:T,source:source.id,rows:[row],origins:[o],artifacts:[]});
const batch=(s,o)=>D("VL-BATCH/1",{trace:T,source:s.body.source,steps:[s],origins:[o],artifacts:[]});
const audit=[];
const append=(data,q)=>{const body={v:1,workspace:W,seq:String(audit.length+1),prev:audit.length?audit.at(-1).hash:ZERO,request:q,key:KA.id,data};const e=signed("VL-AUDIT/1",body,KA);audit.push(e);return e;};
const fixtureConfig={v:1,workspace:W,profile:"fixture-only"};
append({kind:"WorkspaceCreated",config:D("VL-CONFIG/1",fixtureConfig)},id("vlq_","0"));
[SA,SB,SC].forEach((source,i)=>append({kind:"SourceRegistered",source},id("vlq_",String(i+1))));
append({kind:"TraceCreated",trace:T,graph:G0},id("vlq_","4"));
const F0={sources:[SA,SB,SC],trace:{id:T,revision:"0",graph:G0},audit:[...audit]};
const ST={request:req(I,SA,RA,OA),hash:batch(A,OA),stage_id:id("vlq_","5"),commit_id:id("vlq_","6")};
append({kind:"ImportStaged",import:I,trace:T,batch:ST.hash,rows:1},ST.stage_id);
const first=append({kind:"ImportCommitted",import:I,trace:T,revision:"1",graph:D("VL-GRAPH/1",M1),batch:ST.hash},ST.commit_id);
ST.commit={import:I,state:"COMMITTED",trace:T,revision:"1",graph:D("VL-GRAPH/1",M1),added:1,duplicates:0,conflicts:0,audit:first.hash};
[[B,OB,M2,"j","7","8","2"],[C,OC,M3,"h","9","A","3"]].forEach(([s,o,m,c,q1,q2,revision])=>{const importId=id("vli_",c),bh=batch(s,o);append({kind:"ImportStaged",import:importId,trace:T,batch:bh,rows:1},id("vlq_",q1));append({kind:"ImportCommitted",import:importId,trace:T,revision,graph:D("VL-GRAPH/1",m),batch:bh},id("vlq_",q2));});
const pin=(k,role,source,last_seq)=>({id:k.id,public:k.public,role,workspace:W,source,stream:source===null?null:"main",first_seq:"1",last_seq,status:"ACTIVE"});
const head=(role,source,e)=>({role,source,stream:source===null?null:"main",seq:e.body.seq,hash:e.hash});
const trust={v:1,workspace:W,keys:[pin(KA,"audit",null,"11"),pin(K1,"origin",SA.id,"1"),pin(K2,"origin",SB.id,"1"),pin(K3,"origin",SC.id,"1")],heads:[head("audit",null,audit.at(-1)),head("origin",SA.id,OA),head("origin",SB.id,OB),head("origin",SC.id,OC)]};
const path_request={trace:T,revision:"3",action:{source:SC.id,record:"c"},max_depth:256,max_nodes:4096};
const graph_hash=D("VL-GRAPH/1",M3);
const path={trace:T,revision:"3",graph:graph_hash,action:C.hash,steps:[A,B,C],origins:sorted([OA,OB,OC]),edges:[AB,BC].sort((a,b)=>a.hash<b.hash?-1:1),gaps:[],structural:"COMPLETE_RELATIVE",evidence:"CLAIMED",disclosure:"NORMALIZED_ONLY"};
const item=(kind,obj)=>({kind,digest:H(J(obj)),bytes:String(J(obj).length)});
const inventory=[...[A,B,C].map(x=>item("step",x)),...[OA,OB,OC].map(x=>item("origin",x)),...audit.map(x=>item("audit",x))].sort((a,b)=>a.kind<b.kind?-1:a.kind>b.kind?1:a.digest<b.digest?-1:1);
const body={v:1,format:"vislineage-bundle/1",workspace:W,trace:T,revision:"3",graph:M3,path_request,path,inventory,attachment_policy:"OMIT",disclosure:"NORMALIZED_ONLY",trust_required:true};
const bundle={body,hash:D("VL-BUNDLE/1",body),steps:[A,B,C].sort((a,b)=>a.hash<b.hash?-1:1),origins:sorted([OA,OB,OC]),audit:[...audit],attachments:[]};
const sunlight={v:1,kind:"action-lineage",format:"vislineage-bundle/1",bundle:bundle.hash,action:C.hash,trace:T,graph:graph_hash,disclosure:"NORMALIZED_ONLY",semantics:"NOT_VERIFIED"};
const verification={integrity:"VALID",structural:"COMPLETE_RELATIVE",origin:"TRUSTED_AT_PIN",audit:"TRUSTED_AT_PIN",disclosure:"NORMALIZED_ONLY",semantics:"NOT_VERIFIED",current_authority:"UNKNOWN",reasons:[]};
const F={graph_hash,path_request,path,bundle,sunlight,trust,verification};
const pair=(method,params,result,q=Q)=>({request:{id:q,method,params},response:{id:q,ok:true,result}});
const examples=[pair("source.register",SA,SA),pair("source.list",{},{sources:[SA,SB,SC]}),pair("trace.create",{trace:T},{id:T,revision:"0",graph:G0}),pair("trace.get",{trace:T},{id:T,revision:"3",graph:F.graph_hash}),pair("import.stage",ST.request,{import:I,state:"STAGED",batch:ST.hash,rows:1,warnings:[]},ST.stage_id),pair("import.get",{import:I},{import:I,state:"STAGED",batch:ST.hash,commit:null,reason:null}),pair("import.commit",{import:I,expected_revision:"0"},ST.commit,ST.commit_id),pair("import.cancel",{import:I},{import:I,state:"CANCELLED"}),pair("path.get",F.path_request,F.path),pair("bundle.export",{path:F.path_request,attachments:"OMIT"},{bundle:F.bundle,sunlight:F.sunlight}),pair("bundle.verify",{bundle:F.bundle,trust:F.trust},F.verification)];
console.log(JSON.stringify({W,T,I,Q,SA,SB,SC,A,B,C,OA,OB,OC,AB,BC,F0,ST,F,examples},null,2));
